name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      # - name: Run Migrate
      #   run: php artisan migrate

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ormeco-kps-laravel-firebase-auth-nginx-aws:14.0 --no-cache .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ormeco-kps-laravel-firebase-auth-nginx-aws:14.0



      #  # Configure AWS CLI with credentials from secrets
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-northeast-1 # Replace with your AWS region, e.g., us-west-2

      # # Log in to AWS ECR
      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   run: |
      #     aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 407095008364.dkr.ecr.ap-northeast-1.amazonaws.com

      # # Build and push your Docker image to ECR
      # - name: Build and push Docker image
      #   run: |
        
      #     docker build -t ormeco-kps-laravel-firebase-auth-planetscale-nginx-aws:9.0 --no-cache .
      #     docker tag ormeco-kps-laravel-firebase-auth-planetscale-nginx-aws:9.0 407095008364.dkr.ecr.ap-northeast-1.amazonaws.com/ormeco-kps-laravel-firebase-auth-planetscale-nginx-aws:9.0
      #     docker push 407095008364.dkr.ecr.ap-northeast-1.amazonaws.com/ormeco-kps-laravel-firebase-auth-planetscale-nginx-aws:9.0
