apiVersion: v1
kind: Service
metadata:
  name: ormeco-service
spec:
  type: NodePort
  selector:
    app: ormeco-kps-laravel-firebase-auth-planetscale-nginx-aws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
