name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub Repositories
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Run migration
      run: php artisan migrate
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ormecokpsnz:3.0 .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ormecokpsnz:3.0
      
    
